"Don't be compatible with vi
set nocompatible

"Using pathogen to load plugins
filetype off
let g:pathogen_disabled = ['pathogen']  "Prevent pathogen from self-sourcing
call pathogen#infect()
call pathogen#helptags()

"Default files encoding and format
scriptencoding utf-8
set encoding=utf-8
set termencoding=utf-8
set fileencoding=utf-8
set fileformats=unix,dos,mac

"Filetype plugin
filetype on
filetype plugin on
filetype indent on

"Theme settings
set termguicolors
syntax on
colorscheme molokai

"Basic settings
set title
set cursorline
set ruler
set number
set colorcolumn=80
set laststatus=2
set signcolumn=yes
set ttyfast
set mousehide
set backspace=indent,eol,start
set splitright
set splitbelow

"Don't create backup
set nobackup
set nowritebackup

"Spaces instead of tabs
set autoindent
set smartindent
set smarttab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

"Search options
set hlsearch    "Highlight results
set incsearch   "Search as you write
set ignorecase  "Search case-insensitive terms
set smartcase   "Use capital letters to search case-sensitive terms

"Treat long lines as break lines
nmap j gj
vmap j gj
nmap k gk
vmap k gk

"Highlight trailing whitespaces
highlight TrailWhitespace ctermbg=red guibg=red
match TrailWhitespace /\s\+$\| \+\ze\t/

"Wrap markdown long lines
autocmd BufNewFile,BufRead *.md set wrap linebreak nolist
autocmd BufNewFile,BufRead *.md set columns=80

"Don't create netrwhist
let g:netrw_dirhistmax = 0
